#!/bin/bash

# Graphs disk usage of up to five paths. Any more might make the graph
# unreadable. To graph more paths, you should create multiple profiles
#
# Usage
# =====
#
# - put this script-file somewhere and make it executable
#
# - create a symlink to your munin-plugins folder (appending a profile name)::
#
#       ln -s <path/to/du_> </path/to/munin-plugins/du_profilename>
#
# - write a profile config for this plugin::
#
#       [du_system]
#       user root
#       env.PATH1 /var/cache/apt-proxy
#       env.PATH2 /var/log
#
# Remember: You can only specify up to 5 paths. For more paths you need to
# link a new profile, and create a corresponding config.
#

function get_size() {
    if [ $# != 2 ]; then
        return
    fi

    PATH=$1
    if [ "${PATH}" ]; then
        SIZE=$(/usr/bin/du -bs ${PATH} | /usr/bin/cut -f 1)
        echo "${2}.value ${SIZE}"
    fi
}

case $1 in
    config)
        echo "graph_title Per-Folder disk usage (profile $(basename $0))"
        echo "graph_vlabel size"
        echo "graph_args --base 1024 -l 0"
        echo "graph_category disk"
        if [ ${PATH1} ]; then
            echo "path1.label ${PATH1}"
            echo "path1.draw AREA"
        fi

        if [ ${PATH2} ]; then
            echo "path2.label ${PATH2}"
            echo "path2.draw STACK"
        fi


        if [ ${PATH3} ]; then
            echo "path3.label ${PATH3}"
            echo "path3.draw STACK"
        fi


        if [ ${PATH4} ]; then
            echo "path4.label ${PATH4}"
            echo "path4.draw STACK"
        fi


        if [ ${PATH5} ]; then
            echo "path5.label ${PATH5}"
            echo "path5.draw STACK"
        fi

    exit 0;;
esac

get_size ${PATH1} "path1"
get_size ${PATH2} "path2"
get_size ${PATH3} "path3"
get_size ${PATH4} "path4"
get_size ${PATH5} "path5"
